#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2017 wystan
 *
 *       filename: bdd_in_browser.js
 *    description:
 *        created: 2017-11-30 10:59:19
 *         author: wystan
 *
 *********************************************************************************
 */


var express = require('express');
var app = express();
app.use(express.static('static'));
app.listen(8080);
console.log("try: http://localhost:8080");

/************************************* END **************************************/

